// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    conversationRows,
    messageRows,
    conversationMcpServerRows,
    toolEventRows,
    geminiThoughtSignatureRows,
    chatStorageMetaRows,
    idxConversationsUpdatedAt,
    idxConversationsAssistant,
    idxMessagesConversationOrder,
    idxMessagesConversationTimestamp,
    idxMessagesGroup,
  ];
  late final Shape0 conversationRows = Shape0(
    source: i0.VersionedTable(
      entityName: 'conversation_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_6,
        _column_7,
        _column_8,
        _column_9,
        _column_10,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 messageRows = Shape1(
    source: i0.VersionedTable(
      entityName: 'message_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_11,
        _column_12,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_17,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_28,
        _column_29,
        _column_30,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 conversationMcpServerRows = Shape2(
    source: i0.VersionedTable(
      entityName: 'conversation_mcp_server_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(conversation_id, server_id)'],
      columns: [_column_11, _column_31, _column_32],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 toolEventRows = Shape3(
    source: i0.VersionedTable(
      entityName: 'tool_event_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(message_id)'],
      columns: [_column_33, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 geminiThoughtSignatureRows = Shape4(
    source: i0.VersionedTable(
      entityName: 'gemini_thought_signature_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(message_id)'],
      columns: [_column_33, _column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 chatStorageMetaRows = Shape5(
    source: i0.VersionedTable(
      entityName: 'chat_storage_meta_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_36, _column_37],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxConversationsUpdatedAt = i1.Index(
    'idx_conversations_updated_at',
    'CREATE INDEX idx_conversations_updated_at ON conversation_rows (updated_at)',
  );
  final i1.Index idxConversationsAssistant = i1.Index(
    'idx_conversations_assistant',
    'CREATE INDEX idx_conversations_assistant ON conversation_rows (assistant_id)',
  );
  final i1.Index idxMessagesConversationOrder = i1.Index(
    'idx_messages_conversation_order',
    'CREATE INDEX idx_messages_conversation_order ON message_rows (conversation_id, message_order)',
  );
  final i1.Index idxMessagesConversationTimestamp = i1.Index(
    'idx_messages_conversation_timestamp',
    'CREATE INDEX idx_messages_conversation_timestamp ON message_rows (conversation_id, timestamp)',
  );
  final i1.Index idxMessagesGroup = i1.Index(
    'idx_messages_group',
    'CREATE INDEX idx_messages_group ON message_rows (group_id)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get title =>
      columnsByName['title']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isPinned =>
      columnsByName['is_pinned']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get assistantId =>
      columnsByName['assistant_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get truncateIndex =>
      columnsByName['truncate_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get versionSelectionsJson =>
      columnsByName['version_selections_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get summary =>
      columnsByName['summary']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get lastSummarizedMessageCount =>
      columnsByName['last_summarized_message_count']!
          as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get chatSuggestionsJson =>
      columnsByName['chat_suggestions_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'title',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_2(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_pinned',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_pinned IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'assistant_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_6(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'truncate_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT (-1)',
      defaultValue: const i1.CustomExpression('-1'),
    );
i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'version_selections_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'{}\'',
      defaultValue: const i1.CustomExpression('\'{}\''),
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'summary',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_9(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_summarized_message_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'chat_suggestions_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL DEFAULT \'[]\'',
      defaultValue: const i1.CustomExpression('\'[]\''),
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get content =>
      columnsByName['content']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get timestamp =>
      columnsByName['timestamp']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get modelId =>
      columnsByName['model_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get providerId =>
      columnsByName['provider_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get totalTokens =>
      columnsByName['total_tokens']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isStreaming =>
      columnsByName['is_streaming']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get reasoningText =>
      columnsByName['reasoning_text']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get reasoningStartAt =>
      columnsByName['reasoning_start_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get reasoningFinishedAt =>
      columnsByName['reasoning_finished_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get translation =>
      columnsByName['translation']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get reasoningSegmentsJson =>
      columnsByName['reasoning_segments_json']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get groupId =>
      columnsByName['group_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get version =>
      columnsByName['version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get promptTokens =>
      columnsByName['prompt_tokens']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get completionTokens =>
      columnsByName['completion_tokens']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get cachedTokens =>
      columnsByName['cached_tokens']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get durationMs =>
      columnsByName['duration_ms']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get messageOrder =>
      columnsByName['message_order']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_11(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'conversation_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES conversation_rows(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_12(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'role',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'content',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_14(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'timestamp',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'model_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_16(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'provider_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_tokens',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_18(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_streaming',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_streaming IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reasoning_text',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reasoning_start_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_21(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'reasoning_finished_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'translation',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reasoning_segments_json',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'group_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'prompt_tokens',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_27(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'completion_tokens',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_28(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cached_tokens',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_29(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_30(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'message_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get serverId =>
      columnsByName['server_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get ordinal =>
      columnsByName['ordinal']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'server_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ordinal',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get messageId =>
      columnsByName['message_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get eventsJson =>
      columnsByName['events_json']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_33(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'message_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES message_rows(id)ON DELETE CASCADE',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'events_json',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get messageId =>
      columnsByName['message_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get signature =>
      columnsByName['signature']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'signature',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get key =>
      columnsByName['key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get value =>
      columnsByName['value']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    conversationRows,
    messageRows,
    conversationMcpServerRows,
    toolEventRows,
    geminiThoughtSignatureRows,
    chatStorageMetaRows,
    idxConversationsUpdatedAt,
    idxConversationsAssistant,
    idxMessagesConversationOrder,
    idxMessagesConversationTimestamp,
    idxMessagesGroup,
  ];
  late final Shape0 conversationRows = Shape0(
    source: i0.VersionedTable(
      entityName: 'conversation_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_38,
        _column_7,
        _column_8,
        _column_39,
        _column_10,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 messageRows = Shape1(
    source: i0.VersionedTable(
      entityName: 'message_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(conversation_id, message_order)',
        'UNIQUE(conversation_id, group_id, version)',
      ],
      columns: [
        _column_0,
        _column_11,
        _column_40,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_41,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 conversationMcpServerRows = Shape2(
    source: i0.VersionedTable(
      entityName: 'conversation_mcp_server_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(conversation_id, server_id)',
        'UNIQUE(conversation_id, ordinal)',
      ],
      columns: [_column_11, _column_31, _column_48],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 toolEventRows = Shape3(
    source: i0.VersionedTable(
      entityName: 'tool_event_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(message_id)'],
      columns: [_column_33, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 geminiThoughtSignatureRows = Shape4(
    source: i0.VersionedTable(
      entityName: 'gemini_thought_signature_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(message_id)'],
      columns: [_column_33, _column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 chatStorageMetaRows = Shape5(
    source: i0.VersionedTable(
      entityName: 'chat_storage_meta_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_36, _column_37],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxConversationsUpdatedAt = i1.Index(
    'idx_conversations_updated_at',
    'CREATE INDEX idx_conversations_updated_at ON conversation_rows (updated_at DESC, id ASC)',
  );
  final i1.Index idxConversationsAssistant = i1.Index(
    'idx_conversations_assistant',
    'CREATE INDEX idx_conversations_assistant ON conversation_rows (assistant_id)',
  );
  final i1.Index idxMessagesConversationOrder = i1.Index(
    'idx_messages_conversation_order',
    'CREATE INDEX idx_messages_conversation_order ON message_rows (conversation_id, message_order, id)',
  );
  final i1.Index idxMessagesConversationTimestamp = i1.Index(
    'idx_messages_conversation_timestamp',
    'CREATE INDEX idx_messages_conversation_timestamp ON message_rows (conversation_id, timestamp, id)',
  );
  final i1.Index idxMessagesGroup = i1.Index(
    'idx_messages_group',
    'CREATE INDEX idx_messages_group ON message_rows (conversation_id, group_id, version, id)',
  );
}

i1.GeneratedColumn<int> _column_38(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'truncate_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT (-1) CHECK (truncate_index >= -1)',
      defaultValue: const i1.CustomExpression('-1'),
    );
i1.GeneratedColumn<int> _column_39(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'last_summarized_message_count',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints:
          'NOT NULL DEFAULT 0 CHECK (last_summarized_message_count >= 0)',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'role',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL CHECK (role IS NOT \'\')',
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'total_tokens',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (total_tokens >= 0)',
    );
i1.GeneratedColumn<int> _column_42(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (version >= 0)',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<int> _column_43(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'prompt_tokens',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (prompt_tokens >= 0)',
    );
i1.GeneratedColumn<int> _column_44(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'completion_tokens',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (completion_tokens >= 0)',
    );
i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'cached_tokens',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (cached_tokens >= 0)',
    );
i1.GeneratedColumn<int> _column_46(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'duration_ms',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL CHECK (duration_ms >= 0)',
    );
i1.GeneratedColumn<int> _column_47(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'message_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (message_order >= 0)',
    );
i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'ordinal',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (ordinal >= 0)',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    conversationRows,
    messageRows,
    conversationMcpServerRows,
    toolEventRows,
    geminiThoughtSignatureRows,
    chatStorageMetaRows,
    messageSlotRows,
    messageRevisionRows,
    conversationBranchRows,
    conversationStateRows,
    idxConversationsUpdatedAt,
    idxConversationsAssistant,
    idxMessagesConversationOrder,
    idxMessagesConversationTimestamp,
    idxMessagesGroup,
    idxMessageSlotsConversationCreated,
    idxMessageRevisionsParent,
    idxMessageRevisionsSlotVersion,
    idxConversationBranchesLeaf,
    idxConversationBranchesParent,
  ];
  late final Shape0 conversationRows = Shape0(
    source: i0.VersionedTable(
      entityName: 'conversation_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_38,
        _column_7,
        _column_8,
        _column_39,
        _column_10,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 messageRows = Shape1(
    source: i0.VersionedTable(
      entityName: 'message_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(conversation_id, message_order)',
        'UNIQUE(conversation_id, group_id, version)',
      ],
      columns: [
        _column_0,
        _column_11,
        _column_40,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_41,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 conversationMcpServerRows = Shape2(
    source: i0.VersionedTable(
      entityName: 'conversation_mcp_server_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(conversation_id, server_id)',
        'UNIQUE(conversation_id, ordinal)',
      ],
      columns: [_column_11, _column_31, _column_48],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 toolEventRows = Shape3(
    source: i0.VersionedTable(
      entityName: 'tool_event_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(message_id)'],
      columns: [_column_33, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 geminiThoughtSignatureRows = Shape4(
    source: i0.VersionedTable(
      entityName: 'gemini_thought_signature_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(message_id)'],
      columns: [_column_33, _column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 chatStorageMetaRows = Shape5(
    source: i0.VersionedTable(
      entityName: 'chat_storage_meta_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_36, _column_37],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 messageSlotRows = Shape6(
    source: i0.VersionedTable(
      entityName: 'message_slot_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(conversation_id, id)'],
      columns: [_column_0, _column_11, _column_49, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 messageRevisionRows = Shape7(
    source: i0.VersionedTable(
      entityName: 'message_revision_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(conversation_id, id)',
        'UNIQUE(conversation_id, slot_id, revision_no)',
        'FOREIGN KEY(conversation_id, slot_id)REFERENCES message_slot_rows(conversation_id, id)DEFERRABLE INITIALLY DEFERRED',
        'FOREIGN KEY(conversation_id, parent_revision_id)REFERENCES message_revision_rows(conversation_id, id)DEFERRABLE INITIALLY DEFERRED',
        'CHECK(parent_revision_id IS NULL OR parent_revision_id <> id)',
        'CHECK(updated_at >= created_at)',
        'CHECK(finalized_at IS NULL OR finalized_at >= created_at)',
        'CHECK(deleted_at IS NULL OR deleted_at >= created_at)',
      ],
      columns: [
        _column_0,
        _column_11,
        _column_50,
        _column_51,
        _column_52,
        _column_2,
        _column_3,
        _column_53,
        _column_54,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 conversationBranchRows = Shape8(
    source: i0.VersionedTable(
      entityName: 'conversation_branch_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(conversation_id, id)',
        'FOREIGN KEY(conversation_id, parent_branch_id)REFERENCES conversation_branch_rows(conversation_id, id)DEFERRABLE INITIALLY DEFERRED',
        'FOREIGN KEY(conversation_id, forked_from_revision_id)REFERENCES message_revision_rows(conversation_id, id)DEFERRABLE INITIALLY DEFERRED',
        'FOREIGN KEY(conversation_id, leaf_revision_id)REFERENCES message_revision_rows(conversation_id, id)DEFERRABLE INITIALLY DEFERRED',
        'CHECK(parent_branch_id IS NULL OR parent_branch_id <> id)',
        'CHECK(deleted_at IS NULL OR deleted_at >= created_at)',
      ],
      columns: [
        _column_0,
        _column_11,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_2,
        _column_54,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 conversationStateRows = Shape9(
    source: i0.VersionedTable(
      entityName: 'conversation_state_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(conversation_id)',
        'FOREIGN KEY(conversation_id, active_branch_id)REFERENCES conversation_branch_rows(conversation_id, id)DEFERRABLE INITIALLY DEFERRED',
        'FOREIGN KEY(conversation_id, context_start_revision_id)REFERENCES message_revision_rows(conversation_id, id)DEFERRABLE INITIALLY DEFERRED',
      ],
      columns: [_column_11, _column_59, _column_60, _column_61],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxConversationsUpdatedAt = i1.Index(
    'idx_conversations_updated_at',
    'CREATE INDEX idx_conversations_updated_at ON conversation_rows (updated_at DESC, id ASC)',
  );
  final i1.Index idxConversationsAssistant = i1.Index(
    'idx_conversations_assistant',
    'CREATE INDEX idx_conversations_assistant ON conversation_rows (assistant_id)',
  );
  final i1.Index idxMessagesConversationOrder = i1.Index(
    'idx_messages_conversation_order',
    'CREATE INDEX idx_messages_conversation_order ON message_rows (conversation_id, message_order, id)',
  );
  final i1.Index idxMessagesConversationTimestamp = i1.Index(
    'idx_messages_conversation_timestamp',
    'CREATE INDEX idx_messages_conversation_timestamp ON message_rows (conversation_id, timestamp, id)',
  );
  final i1.Index idxMessagesGroup = i1.Index(
    'idx_messages_group',
    'CREATE INDEX idx_messages_group ON message_rows (conversation_id, group_id, version, id)',
  );
  final i1.Index idxMessageSlotsConversationCreated = i1.Index(
    'idx_message_slots_conversation_created',
    'CREATE INDEX idx_message_slots_conversation_created ON message_slot_rows (conversation_id, created_at, id)',
  );
  final i1.Index idxMessageRevisionsParent = i1.Index(
    'idx_message_revisions_parent',
    'CREATE INDEX idx_message_revisions_parent ON message_revision_rows (conversation_id, parent_revision_id, id)',
  );
  final i1.Index idxMessageRevisionsSlotVersion = i1.Index(
    'idx_message_revisions_slot_version',
    'CREATE INDEX idx_message_revisions_slot_version ON message_revision_rows (conversation_id, slot_id, revision_no DESC, id)',
  );
  final i1.Index idxConversationBranchesLeaf = i1.Index(
    'idx_conversation_branches_leaf',
    'CREATE INDEX idx_conversation_branches_leaf ON conversation_branch_rows (conversation_id, leaf_revision_id, id)',
  );
  final i1.Index idxConversationBranchesParent = i1.Index(
    'idx_conversation_branches_parent',
    'CREATE INDEX idx_conversation_branches_parent ON conversation_branch_rows (conversation_id, parent_branch_id, id)',
  );
}

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get role =>
      columnsByName['role']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_49(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'role',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK (role IN (\'user\', \'assistant\', \'system\', \'tool\'))',
);

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get slotId =>
      columnsByName['slot_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get parentRevisionId =>
      columnsByName['parent_revision_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get revisionNo =>
      columnsByName['revision_no']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get finalizedAt =>
      columnsByName['finalized_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_50(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'slot_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'parent_revision_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_52(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'revision_no',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (revision_no >= 0)',
    );
i1.GeneratedColumn<int> _column_53(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'finalized_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_54(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'deleted_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get id =>
      columnsByName['id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get parentBranchId =>
      columnsByName['parent_branch_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get forkedFromRevisionId =>
      columnsByName['forked_from_revision_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get leafRevisionId =>
      columnsByName['leaf_revision_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get causalityKind =>
      columnsByName['causality_kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get deletedAt =>
      columnsByName['deleted_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_55(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'parent_branch_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'forked_from_revision_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'leaf_revision_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_58(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'causality_kind',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK (causality_kind IN (\'native\', \'legacy_visible_projection\', \'legacy_ambiguous\'))',
);

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get activeBranchId =>
      columnsByName['active_branch_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get contextStartRevisionId =>
      columnsByName['context_start_revision_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get stateRevision =>
      columnsByName['state_revision']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'active_branch_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'context_start_revision_id',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_61(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'state_revision',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (state_revision >= 0)',
      defaultValue: const i1.CustomExpression('0'),
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    conversationRows,
    messageRows,
    conversationMcpServerRows,
    toolEventRows,
    geminiThoughtSignatureRows,
    chatStorageMetaRows,
    messageSlotRows,
    messageRevisionRows,
    conversationBranchRows,
    conversationStateRows,
    messagePartRows,
    idxConversationsUpdatedAt,
    idxConversationsAssistant,
    idxMessagesConversationOrder,
    idxMessagesConversationTimestamp,
    idxMessagesGroup,
    idxMessageSlotsConversationCreated,
    idxMessageRevisionsParent,
    idxMessageRevisionsSlotVersion,
    idxConversationBranchesLeaf,
    idxConversationBranchesParent,
    idxMessagePartsRevisionOrdinal,
  ];
  late final Shape0 conversationRows = Shape0(
    source: i0.VersionedTable(
      entityName: 'conversation_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)'],
      columns: [
        _column_0,
        _column_1,
        _column_2,
        _column_3,
        _column_4,
        _column_5,
        _column_38,
        _column_7,
        _column_8,
        _column_39,
        _column_10,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 messageRows = Shape1(
    source: i0.VersionedTable(
      entityName: 'message_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(conversation_id, message_order)',
        'UNIQUE(conversation_id, group_id, version)',
      ],
      columns: [
        _column_0,
        _column_11,
        _column_40,
        _column_13,
        _column_14,
        _column_15,
        _column_16,
        _column_41,
        _column_18,
        _column_19,
        _column_20,
        _column_21,
        _column_22,
        _column_23,
        _column_24,
        _column_42,
        _column_43,
        _column_44,
        _column_45,
        _column_46,
        _column_47,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 conversationMcpServerRows = Shape2(
    source: i0.VersionedTable(
      entityName: 'conversation_mcp_server_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(conversation_id, server_id)',
        'UNIQUE(conversation_id, ordinal)',
      ],
      columns: [_column_11, _column_31, _column_48],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 toolEventRows = Shape3(
    source: i0.VersionedTable(
      entityName: 'tool_event_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(message_id)'],
      columns: [_column_33, _column_34],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 geminiThoughtSignatureRows = Shape4(
    source: i0.VersionedTable(
      entityName: 'gemini_thought_signature_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(message_id)'],
      columns: [_column_33, _column_35],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 chatStorageMetaRows = Shape5(
    source: i0.VersionedTable(
      entityName: 'chat_storage_meta_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY("key")'],
      columns: [_column_36, _column_37],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 messageSlotRows = Shape6(
    source: i0.VersionedTable(
      entityName: 'message_slot_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(id)', 'UNIQUE(conversation_id, id)'],
      columns: [_column_0, _column_11, _column_49, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 messageRevisionRows = Shape7(
    source: i0.VersionedTable(
      entityName: 'message_revision_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(conversation_id, id)',
        'UNIQUE(conversation_id, slot_id, revision_no)',
        'FOREIGN KEY(conversation_id, slot_id)REFERENCES message_slot_rows(conversation_id, id)DEFERRABLE INITIALLY DEFERRED',
        'FOREIGN KEY(conversation_id, parent_revision_id)REFERENCES message_revision_rows(conversation_id, id)DEFERRABLE INITIALLY DEFERRED',
        'CHECK(parent_revision_id IS NULL OR parent_revision_id <> id)',
        'CHECK(updated_at >= created_at)',
        'CHECK(finalized_at IS NULL OR finalized_at >= created_at)',
        'CHECK(deleted_at IS NULL OR deleted_at >= created_at)',
      ],
      columns: [
        _column_0,
        _column_11,
        _column_50,
        _column_51,
        _column_52,
        _column_2,
        _column_3,
        _column_53,
        _column_54,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 conversationBranchRows = Shape8(
    source: i0.VersionedTable(
      entityName: 'conversation_branch_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(id)',
        'UNIQUE(conversation_id, id)',
        'FOREIGN KEY(conversation_id, parent_branch_id)REFERENCES conversation_branch_rows(conversation_id, id)DEFERRABLE INITIALLY DEFERRED',
        'FOREIGN KEY(conversation_id, forked_from_revision_id)REFERENCES message_revision_rows(conversation_id, id)DEFERRABLE INITIALLY DEFERRED',
        'FOREIGN KEY(conversation_id, leaf_revision_id)REFERENCES message_revision_rows(conversation_id, id)DEFERRABLE INITIALLY DEFERRED',
        'CHECK(parent_branch_id IS NULL OR parent_branch_id <> id)',
        'CHECK(deleted_at IS NULL OR deleted_at >= created_at)',
      ],
      columns: [
        _column_0,
        _column_11,
        _column_55,
        _column_56,
        _column_57,
        _column_58,
        _column_2,
        _column_54,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 conversationStateRows = Shape9(
    source: i0.VersionedTable(
      entityName: 'conversation_state_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(conversation_id)',
        'FOREIGN KEY(conversation_id, active_branch_id)REFERENCES conversation_branch_rows(conversation_id, id)DEFERRABLE INITIALLY DEFERRED',
        'FOREIGN KEY(conversation_id, context_start_revision_id)REFERENCES message_revision_rows(conversation_id, id)DEFERRABLE INITIALLY DEFERRED',
      ],
      columns: [_column_11, _column_59, _column_60, _column_61],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 messagePartRows = Shape10(
    source: i0.VersionedTable(
      entityName: 'message_part_rows',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: [
        'PRIMARY KEY(revision_id, ordinal)',
        'UNIQUE(conversation_id, revision_id, ordinal)',
        'FOREIGN KEY(conversation_id, revision_id)REFERENCES message_revision_rows(conversation_id, id)ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED',
        'CHECK(updated_at >= created_at)',
      ],
      columns: [
        _column_62,
        _column_63,
        _column_48,
        _column_64,
        _column_65,
        _column_2,
        _column_3,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index idxConversationsUpdatedAt = i1.Index(
    'idx_conversations_updated_at',
    'CREATE INDEX idx_conversations_updated_at ON conversation_rows (updated_at DESC, id ASC)',
  );
  final i1.Index idxConversationsAssistant = i1.Index(
    'idx_conversations_assistant',
    'CREATE INDEX idx_conversations_assistant ON conversation_rows (assistant_id)',
  );
  final i1.Index idxMessagesConversationOrder = i1.Index(
    'idx_messages_conversation_order',
    'CREATE INDEX idx_messages_conversation_order ON message_rows (conversation_id, message_order, id)',
  );
  final i1.Index idxMessagesConversationTimestamp = i1.Index(
    'idx_messages_conversation_timestamp',
    'CREATE INDEX idx_messages_conversation_timestamp ON message_rows (conversation_id, timestamp, id)',
  );
  final i1.Index idxMessagesGroup = i1.Index(
    'idx_messages_group',
    'CREATE INDEX idx_messages_group ON message_rows (conversation_id, group_id, version, id)',
  );
  final i1.Index idxMessageSlotsConversationCreated = i1.Index(
    'idx_message_slots_conversation_created',
    'CREATE INDEX idx_message_slots_conversation_created ON message_slot_rows (conversation_id, created_at, id)',
  );
  final i1.Index idxMessageRevisionsParent = i1.Index(
    'idx_message_revisions_parent',
    'CREATE INDEX idx_message_revisions_parent ON message_revision_rows (conversation_id, parent_revision_id, id)',
  );
  final i1.Index idxMessageRevisionsSlotVersion = i1.Index(
    'idx_message_revisions_slot_version',
    'CREATE INDEX idx_message_revisions_slot_version ON message_revision_rows (conversation_id, slot_id, revision_no DESC, id)',
  );
  final i1.Index idxConversationBranchesLeaf = i1.Index(
    'idx_conversation_branches_leaf',
    'CREATE INDEX idx_conversation_branches_leaf ON conversation_branch_rows (conversation_id, leaf_revision_id, id)',
  );
  final i1.Index idxConversationBranchesParent = i1.Index(
    'idx_conversation_branches_parent',
    'CREATE INDEX idx_conversation_branches_parent ON conversation_branch_rows (conversation_id, parent_branch_id, id)',
  );
  final i1.Index idxMessagePartsRevisionOrdinal = i1.Index(
    'idx_message_parts_revision_ordinal',
    'CREATE INDEX idx_message_parts_revision_ordinal ON message_part_rows (conversation_id, revision_id, ordinal)',
  );
}

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get conversationId =>
      columnsByName['conversation_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get revisionId =>
      columnsByName['revision_id']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get ordinal =>
      columnsByName['ordinal']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get kind =>
      columnsByName['kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get payload =>
      columnsByName['payload']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'conversation_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_63(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'revision_id',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_64(
  String aliasedName,
) => i1.GeneratedColumn<String>(
  'kind',
  aliasedName,
  false,
  type: i1.DriftSqlType.string,
  $customConstraints:
      'NOT NULL CHECK (kind IN (\'text\', \'reasoning\', \'tool_call\', \'tool_result\'))',
);
i1.GeneratedColumn<String> _column_65(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'payload',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
  ),
);
