#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
configuration="${OPENMINIS_RUNNER_CONFIGURATION:-Release}"
openminis_configuration="${OPENMINIS_CONFIGURATION:-Release}"
derived_data="${DERIVED_DATA_DIR:-$repo_root/build/openminis-ish-arm64-derived}"
products_dir="$derived_data/Build/Products/$openminis_configuration-iphoneos"
runner_build_dir="${RUNNER_DERIVED_DATA_DIR:-$repo_root/build/ios-openminis-runner}"

"$repo_root/scripts/ios/build_openminis_ish_arm64.sh"

required_libraries=(
  "$products_dir/libish.a"
  "$products_dir/libfakefs.a"
  "$products_dir/libish_emu.a"
)

force_load_libraries=(
  "$products_dir/libish.a"
)

linked_libraries=(
  "$products_dir/libfakefs.a"
  "$products_dir/libish_emu.a"
)

for library in "${required_libraries[@]}"; do
  if [[ ! -f "$library" ]]; then
    echo "error: missing OpenMinis library: $library" >&2
    exit 1
  fi
done

ldflags=(
  '$(inherited)'
  -ObjC
  -Wl,-ld_classic
  -sectalign __DATA __percpu_first 1000
  -sectalign __DATA __tracepoints 20
  -lsqlite3
  -lz
)

for library in "${force_load_libraries[@]}"; do
  ldflags+=(-force_load "$library")
done

for library in "${linked_libraries[@]}"; do
  ldflags+=("$library")
done

if [[ -f "$products_dir/libarchive.a" ]]; then
  ldflags+=("$products_dir/libarchive.a")
fi

cat >"$repo_root/ios/Flutter/OpenMinisTerminal.local.xcconfig" <<EOF
// Generated by scripts/ios/build_runner_with_openminis_ish_arm64.sh.
// This lets Android Studio/Xcode Run reuse the prebuilt OpenMinis iSH ARM64 libraries.
KELIVO_TERMINAL_GCC_DEFINITIONS = KELIVO_OPENMINIS_ISH=1
KELIVO_TERMINAL_HEADER_SEARCH_PATHS = \$(SRCROOT)/../dependencies/ish-arm64/app \$(SRCROOT)/../dependencies/ish-arm64
KELIVO_TERMINAL_LIBRARY_SEARCH_PATHS[sdk=iphoneos*] = \$(SRCROOT)/../build/openminis-ish-arm64-derived/Build/Products/Release-iphoneos \$(SRCROOT)/../build/openminis-ish-arm64-derived/Build/Products/Release-iphoneos/meson
KELIVO_TERMINAL_OTHER_LDFLAGS[sdk=iphoneos*] = -ObjC -Wl,-ld_classic -sectalign __DATA __percpu_first 1000 -sectalign __DATA __tracepoints 20 -lsqlite3 -lz -force_load \$(SRCROOT)/../build/openminis-ish-arm64-derived/Build/Products/Release-iphoneos/libish.a \$(SRCROOT)/../build/openminis-ish-arm64-derived/Build/Products/Release-iphoneos/libfakefs.a \$(SRCROOT)/../build/openminis-ish-arm64-derived/Build/Products/Release-iphoneos/libish_emu.a
ARCHS[sdk=iphonesimulator*] = arm64
ONLY_ACTIVE_ARCH[sdk=iphonesimulator*] = YES
EXCLUDED_ARCHS[sdk=iphonesimulator*] = x86_64
KELIVO_TERMINAL_LIBRARY_SEARCH_PATHS[sdk=iphonesimulator*] = \$(SRCROOT)/../build/openminis-ish-arm64-simulator-derived/Build/Products/Release-iphonesimulator \$(SRCROOT)/../build/openminis-ish-arm64-simulator-derived/Build/Products/Release-iphonesimulator/meson
KELIVO_TERMINAL_OTHER_LDFLAGS[sdk=iphonesimulator*] = -ObjC -Wl,-ld_classic -sectalign __DATA __percpu_first 1000 -sectalign __DATA __tracepoints 20 -lsqlite3 -lz -force_load \$(SRCROOT)/../build/openminis-ish-arm64-simulator-derived/Build/Products/Release-iphonesimulator/libish.a \$(SRCROOT)/../build/openminis-ish-arm64-simulator-derived/Build/Products/Release-iphonesimulator/libfakefs.a \$(SRCROOT)/../build/openminis-ish-arm64-simulator-derived/Build/Products/Release-iphonesimulator/libish_emu.a
EOF

flutter build ios --config-only --no-codesign

xcodebuild \
  -workspace "$repo_root/ios/Runner.xcworkspace" \
  -scheme Runner \
  -configuration "$configuration" \
  -sdk iphoneos \
  -destination 'generic/platform=iOS' \
  SYMROOT="$runner_build_dir/Build/Products" \
  OBJROOT="$runner_build_dir/Build/Intermediates.noindex" \
  CODE_SIGNING_ALLOWED=NO \
  CODE_SIGNING_REQUIRED=NO \
  CODE_SIGN_IDENTITY="" \
  build

echo "Kelivo Runner iOS build finished with OpenMinis iSH ARM64 linked."
echo "Runner build products: $runner_build_dir/Build/Products/$configuration-iphoneos"
